# See https://github.com/crate-ci/typos/blob/master/docs/reference.md to configure typos
[default]
extend-ignore-re = [
    "<thi",
    "bs-BA",
]

[default.extend-words]
Readed = "Readed"
Sie = "Sie"
OT = "OT"
BA = "BA"
tak = "tak"

[files]
extend-exclude = ["public/*", "dist/*", "src/common/geo-data.ts", "pnpm-lock.yaml", "*.storyboard", "src-tauri/gen/*", "src/common/i18n/locales/tr/*"]
