name: Playwright Tests

on:
    push:
        branches:
            - main
    pull_request:
        branches:
            - main

env:
    NODE_VERSION: 18

jobs:
    e2e-test:
        timeout-minutes: 60
        runs-on: ubuntu-22.04
        permissions:
            contents: read

        steps:
            - uses: actions/checkout@v7.0.0

            - uses: pnpm/action-setup@v6.0.8

            - name: Setup Node
              uses: actions/setup-node@v6.4.0
              with:
                  node-version: ${{ env.NODE_VERSION }}
                  cache: pnpm

            - name: Install dependencies
              run: pnpm install --frozen-lockfile

            - name: Install Playwright Browsers
              run: pnpm exec playwright install chromium --with-deps

            - name: Build Chromium extension
              run: pnpm vite build -c vite.config.chromium.ts

            - name: Run Playwright tests
              run: pnpm test:e2e --reporter github
